require 'test_helper'

class ExceptionsControllerTest < ActionController::TestCase
=begin
TODO: get is returning its own error right now, fix.

  test 'render_error' do
    get :render_error
    assert response.body.include? "We've encountered an error."
  end
=end
end
